version: "3.7"

services:

  postgres_db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root

  mysql_db:
    image: "mysql:latest"
    restart: always
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_PASSWORD: root
